#lang sicp

; Exercise 1.9
; Each of the following two procedures defines a method
; for adding two positive integers in terms of the procedures inc, which
; increments its argument by 1, and dec, which decrements its argument by 1.

;Method 1
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

;Method 2
(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by
; each procedure in evaluating (+ 4 5). Are these processes iterative or
; recursive?

; Answer

; The first process is recursive and the second is iterative
; In the first procedure, the increment operation keeps building
; and defering to later
; whereas
; In the second procedure, even though the procedure is recursive,
; the process is iterative with a and b being incremented and
; decremented every step
