#lang sicp
(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine-count angle c)
  (display c)( display " ")(display angle)(newline)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine-count (/ angle 3.0) (+ 1 c)))))

(sine-count 12.15 0)

;How many times is the procedure p applied when (sine 12.15) is evaluated?
; 5

;What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?
(sine-count 10 0) ; 5
(sine-count 100 0) ; 7
(sine-count 1000 0); 9
(sine-count 10000 0) ; 11

; We can see that everytime the angle grows by 10, the number of steps only increases by 2
; This is theta(log a) growth 
